spring:
  application:
    name: spring-boot-tlias
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mozisun.springboottlias.model.entiry
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.boot.context.properties: info
    org.springframework.core.env: info

# application.yml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIBABA_ACCESS_KEY_ID}      # 冒号后有空格！
    accessKeySecret: ${ALIBABA_ACCESS_KEY_SECRET}
    bucketName: chengzi03



alias:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: hasdiofhkljsahdfljkhsadbnfklasbdfjihsadflkjhasdlkjfhsidlfuhasdkjlfhbasdkflghskludjfh
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packagesToScan:
    - com.mozisun.springboottlias.controller


knife4j:
  enable: true

